export const currencies = [
  { code: "USD", label: "US Dollar ($)" },
  { code: "EUR", label: "Euro (€)" },
  { code: "GBP", label: "British Pound (£)" },
  { code: "INR", label: "Indian Rupee (₹)" },
  { code: "BDT", label: "Bangladeshi Taka (৳)" },
  { code: "JPY", label: "Japanese Yen (¥)" },
  { code: "AUD", label: "Australian Dollar (A$)" },
  { code: "CAD", label: "Canadian Dollar (C$)" },
  { code: "CHF", label: "Swiss Franc (CHF)" },
  { code: "CNY", label: "Chinese Yuan (¥)" },
  { code: "SGD", label: "Singapore Dollar (S$)" },
  { code: "NZD", label: "New Zealand Dollar (NZ$)" },
  { code: "ZAR", label: "South African Rand (R)" },
  { code: "HKD", label: "Hong Kong Dollar (HK$)" },
  { code: "KRW", label: "South Korean Won (₩)" },
  { code: "MXN", label: "Mexican Peso (MX$)" },
  { code: "BRL", label: "Brazilian Real (R$)" },
  { code: "RUB", label: "Russian Ruble (₽)" },
  { code: "TRY", label: "Turkish Lira (₺)" },
  { code: "SAR", label: "Saudi Riyal (SAR)" },
  { code: "AED", label: "UAE Dirham (AED)" },
  { code: "PKR", label: "Pakistani Rupee (₨)" },
  { code: "EGP", label: "Egyptian Pound (E£)" },
  { code: "NGN", label: "Nigerian Naira (₦)" },
  { code: "IDR", label: "Indonesian Rupiah (Rp)" },
  { code: "MYR", label: "Malaysian Ringgit (RM)" },
  { code: "THB", label: "Thai Baht (฿)" },
  { code: "VND", label: "Vietnamese Dong (₫)" },
  { code: "PHP", label: "Philippine Peso (₱)" },
  { code: "CLP", label: "Chilean Peso (CLP$)" },
  { code: "ARS", label: "Argentine Peso (AR$)" },
  { code: "DKK", label: "Danish Krone (kr)" },
  { code: "NOK", label: "Norwegian Krone (kr)" },
  { code: "SEK", label: "Swedish Krona (kr)" },
  { code: "PLN", label: "Polish Złoty (zł)" },
  { code: "ILS", label: "Israeli Shekel (₪)" },
  { code: "KWD", label: "Kuwaiti Dinar (KD)" },
  { code: "QAR", label: "Qatari Riyal (QAR)" },
  { code: "OMR", label: "Omani Rial (OMR)" },
  { code: "JOD", label: "Jordanian Dinar (JOD)" },
  { code: "TWD", label: "New Taiwan Dollar (NT$)" },
  { code: "CZK", label: "Czech Koruna (Kč)" },
  { code: "HUF", label: "Hungarian Forint (Ft)" },
  { code: "UAH", label: "Ukrainian Hryvnia (₴)" }
];